# Generated by Django 5.2.4 on 2026-06-23 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tastes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_genre_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'genre_names',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.PositiveBigIntegerField(unique=True)),
                ('original_title', models.CharField(max_length=500)),
                ('original_language', models.CharField(max_length=10)),
                ('english_name', models.CharField(blank=True, max_length=100, null=True)),
                ('poster_path', models.CharField(max_length=500)),
                ('backdrop_path', models.CharField(blank=True, max_length=500, null=True)),
                ('release_date', models.DateField()),
                ('vote_average', models.FloatField()),
                ('vote_count', models.PositiveIntegerField(blank=True, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('softcore', models.BooleanField(blank=True, null=True)),
                ('video', models.BooleanField(blank=True, null=True)),
                ('content_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='movie_detail', to='tastes.contentitem')),
            ],
            options={
                'db_table': 'movie_details',
                'ordering': ['-release_date', '-popularity'],
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_links', to='movies.genrename')),
                ('movie_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_links', to='movies.moviedetail')),
            ],
            options={
                'db_table': 'movie_genres',
            },
        ),
        migrations.AddField(
            model_name='genrename',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='genres', through='movies.MovieGenre', to='movies.moviedetail'),
        ),
        migrations.AddIndex(
            model_name='moviedetail',
            index=models.Index(fields=['release_date'], name='movie_release_idx'),
        ),
        migrations.AddIndex(
            model_name='moviedetail',
            index=models.Index(fields=['vote_average'], name='movie_vote_avg_idx'),
        ),
        migrations.AddConstraint(
            model_name='moviegenre',
            constraint=models.UniqueConstraint(fields=('movie_detail', 'genre_name'), name='unique_movie_genre'),
        ),
    ]
