# Generated by Django 5.2.4 on 2026-06-23 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tastes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(blank=True, max_length=500, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('sigungu', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'places',
                'ordering': ['area', 'sigungu', 'place_name'],
                'indexes': [models.Index(fields=['area', 'sigungu'], name='place_region_idx')],
                'constraints': [models.UniqueConstraint(fields=('place_name', 'address'), name='unique_place_name_address')],
            },
        ),
        migrations.CreateModel(
            name='CultureEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.CharField(max_length=100, unique=True)),
                ('main_category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('realm_code', models.CharField(blank=True, max_length=50, null=True)),
                ('realm_name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=500, null=True)),
                ('is_map_available', models.BooleanField(default=False)),
                ('content_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='culture_event', to='tastes.contentitem')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='culture_events', to='cultures.place')),
            ],
            options={
                'db_table': 'culture_events',
                'ordering': ['end_date', 'start_date'],
                'indexes': [models.Index(fields=['main_category'], name='culture_main_cat_idx'), models.Index(fields=['sub_category'], name='culture_sub_cat_idx'), models.Index(fields=['start_date', 'end_date'], name='culture_period_idx')],
            },
        ),
    ]
