# Generated by Django 5.2.4 on 2026-06-23 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('movie', '영화'), ('book', '도서'), ('culture', '문화')], max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(max_length=1000)),
                ('source_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('is_adult', models.BooleanField(default=False)),
                ('popularity_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'content_items',
                'ordering': ['-popularity_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('keyword_type', models.CharField(choices=[('movie', '영화'), ('book', '도서'), ('culture', '문화'), ('common', '공통')], max_length=20)),
            ],
            options={
                'db_table': 'keywords',
                'ordering': ['keyword_type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'keyword_type'), name='unique_keyword_name_type')],
            },
        ),
        migrations.CreateModel(
            name='ContentKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_keyword_links', to='tastes.contentitem')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_keyword_links', to='tastes.keyword')),
            ],
            options={
                'db_table': 'content_keywords',
            },
        ),
        migrations.AddField(
            model_name='contentitem',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='content_items', through='tastes.ContentKeyword', to='tastes.keyword'),
        ),
        migrations.CreateModel(
            name='TasteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('TREND', '유행 탑승형'), ('MONGLE', '마음 몽글형'), ('WORLD', '세계관 과몰입형'), ('KNOWLEDGE', '지식 냠냠형'), ('FESTIVAL', '축제 팔랑귀형'), ('TOGETHER', '같이보기 찰떡형')], max_length=20)),
                ('result_summary', models.TextField()),
                ('score_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keywords', models.ManyToManyField(blank=True, related_name='taste_results', to='tastes.keyword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taste_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'taste_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0)),
                ('source_type', models.CharField(choices=[('test', '취향 테스트'), ('selected', '직접 선택'), ('feedback', '콘텐츠 반응')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_keywords', to='tastes.keyword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_keywords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_keywords',
            },
        ),
        migrations.CreateModel(
            name='ContentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('like', '좋아요'), ('dislike', '싫어요')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='tastes.contentitem')),
            ],
            options={
                'db_table': 'content_feedbacks',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'content_item'), name='unique_user_content_feedback')],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='tastes.contentitem')),
            ],
            options={
                'db_table': 'bookmarks',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'content_item'), name='unique_user_bookmark')],
            },
        ),
        migrations.AddConstraint(
            model_name='contentkeyword',
            constraint=models.UniqueConstraint(fields=('content_item', 'keyword'), name='unique_content_keyword'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['content_type'], name='content_type_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['title'], name='content_title_idx'),
        ),
        migrations.AddConstraint(
            model_name='userkeyword',
            constraint=models.UniqueConstraint(fields=('user', 'keyword', 'source_type'), name='unique_user_keyword_source'),
        ),
    ]
