# Generated by Django 5.2.4 on 2026-06-24 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tastes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasteQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.PositiveSmallIntegerField(unique=True)),
                ('order_no', models.PositiveSmallIntegerField(unique=True)),
                ('question_text', models.TextField()),
            ],
            options={
                'db_table': 'taste_questions',
                'ordering': ['order_no'],
            },
        ),
        migrations.CreateModel(
            name='TasteTestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(default='default', max_length=50, unique=True)),
                ('test_meta', models.JSONField(default=dict)),
                ('calculation_policy', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'taste_test_configs',
            },
        ),
        migrations.CreateModel(
            name='TasteTypeDefinition',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_type', models.CharField(max_length=100)),
                ('subtitle', models.TextField()),
                ('summary', models.TextField()),
                ('description', models.JSONField(default=list)),
                ('keywords', models.JSONField(default=list)),
                ('recommendation_guide', models.JSONField(default=dict)),
                ('recommendation_db_mapping', models.JSONField(default=dict)),
                ('result_keywords', models.JSONField(default=list)),
                ('character_concept', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'taste_type_definitions',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TasteScoreRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.BooleanField()),
                ('score', models.FloatField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_rules', to='tastes.tastequestion')),
                ('result_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_rules', to='tastes.tastetypedefinition')),
            ],
            options={
                'db_table': 'taste_score_rules',
                'ordering': ['question__order_no', 'answer_value'],
                'constraints': [models.UniqueConstraint(fields=('question', 'answer_value'), name='unique_taste_question_answer_rule')],
            },
        ),
    ]
