# Generated by Django 5.2.4 on 2026-06-23 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tastes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'verbose_name_plural': 'book categories',
                'db_table': 'book_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveBigIntegerField(unique=True)),
                ('isbn10', models.CharField(blank=True, max_length=20, null=True)),
                ('isbn13', models.CharField(blank=True, max_length=20, null=True)),
                ('author', models.CharField(max_length=500)),
                ('publisher', models.CharField(max_length=255)),
                ('pub_date', models.DateField()),
                ('sales_point', models.PositiveIntegerField(blank=True, null=True)),
                ('customer_review_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('content_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_detail', to='tastes.contentitem')),
            ],
            options={
                'db_table': 'book_details',
                'ordering': ['-pub_date', '-sales_point'],
            },
        ),
        migrations.CreateModel(
            name='BookCategoryMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_links', to='books.bookcategory')),
                ('book_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='books.bookdetail')),
            ],
            options={
                'db_table': 'book_category_map',
            },
        ),
        migrations.AddField(
            model_name='bookcategory',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='categories', through='books.BookCategoryMap', to='books.bookdetail'),
        ),
        migrations.AddConstraint(
            model_name='bookcategorymap',
            constraint=models.UniqueConstraint(fields=('book_detail', 'category'), name='unique_book_category'),
        ),
    ]
