# Generated by Django 5.2.4 on 2026-06-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcategory',
            name='aladin_category_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bookdetail',
            name='fixed_price',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookdetail',
            name='has_ebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookdetail',
            name='mall_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookdetail',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookdetail',
            name='price_sales',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookdetail',
            name='price_standard',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookdetail',
            name='series_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookdetail',
            name='stock_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
